[service]
# 端口
port=10086
# mongo地址
mongo="mongodb://localhost:27017"


[rabbitmq]
#消息队列服务器地址
server="127.0.0.1"
#端口
port=1883
#主题
topic="topic.clientlog"
#自身连接的clientid
clientid="ylz_log_viewer"
#不加延时publish会失败单位毫秒
sleep=200

user="clientlog"
password="clientlog"

[client]
root="E:/Work/logs"

[[service_log]]
code="1"
title="住院收费"
dir="E:/Work/logs/jdbc"

[[service_log]]
code="2"
title="门诊收费"
dir="E:/Work/logs/trace"

[[service_log]]
code="3"
title="药库"
dir="E:/Work/logs/trace"

[files]
encoding="UTF8"